package Economia.Tramite90101;
import com.codeborne.selenide.Selenide;
import com.codeborne.selenide.SelenideElement;
public class MainPage90101 {
    public SelenideElement cerS = Selenide.$x("//*[@id='certificate']");
    public SelenideElement keyS = Selenide.$x("//*[@id='privateKey']");
    public SelenideElement pass = Selenide.$x("//*[@id='privateKeyPassword']");
    public SelenideElement btnIngres = Selenide.$x("//button[@onclick='ejecutarProcesoFirma(1)']");
    public SelenideElement selecRol = Selenide.$x("//*[@id='claveRol']");
    public SelenideElement btnacep = Selenide.$x("//button[@name='ingresar']");
    public SelenideElement Tramites = Selenide.$x("//*[@id='Trámites']");
    public SelenideElement SoliNew = Selenide.$x("/html/body/main/div/div[2]/div[1]/div[1]/div/nav/div/div[2]/ul/li[5]/ul/li[3]/a");
    public SelenideElement economia = Selenide.$x("/html/body/main/div/div[3]/div/form/a[2]/img");
    public SelenideElement prosec = Selenide.$x("/html/body/main/div/div[3]/div/div[6]/ul/li[2]/a");
    public SelenideElement programaNuevo = Selenide.$x("/html/body/main/div/div[3]/div/div[6]/ul/li[2]/ul/li[1]/a");
    public SelenideElement productorDirecto = Selenide.$x("/html/body/main/div/div[3]/div/div[6]/ul/li[2]/ul/li[1]/ul/li[1]/a");
    public SelenideElement domiciliosPlantas = Selenide.$x("/html/body/main/div/div[4]/div/form/div[2]/ul/li[2]/a/label");
    public SelenideElement estadoPlantas = Selenide.$x("//*[@id='entidadFederativaDomicilios']");
    public SelenideElement mostrarDomicilios = Selenide.$x("/html/body/main/div/div[4]/div/form/div[2]/div[2]/div[4]/div[2]/div/input");
    public SelenideElement seleccionaPlanta = Selenide.$x("//*[@id='jqg_gridPlantasPROSECDisponibles_1']");
    public SelenideElement agregarPlanta = Selenide.$x("//*[@id='agregar_plantas']");
    public SelenideElement actividadProductiva = Selenide.$x("//*[@id='actividadProductiva']");
    public SelenideElement sectoresMercancias = Selenide.$x("/html/body/main/div/div[4]/div/form/div[2]/ul/li[3]/a/label");
    public SelenideElement sector = Selenide.$x("//*[@id='sectoresProsecConf']");
    public SelenideElement agregarSector = Selenide.$x("/html/body/main/div/div[4]/div/form/div[2]/div[3]/div[4]/div/div/div/input[2]");
    public SelenideElement selecSector = Selenide.$x("/html/body/main/div/div[4]/div/form/div[2]/div[3]/div[6]/div/div[1]/div/div[3]/div[3]/div/table/tbody/tr[2]/td[1]/input");
    public SelenideElement fraccionArancelaria = Selenide.$x("/html/body/main/div/div[4]/div/form/div[2]/div[3]/div[7]/div[3]/div/div/input");
    public SelenideElement agregarFraccion = Selenide.$x("//*[@id='btnAgregarFraccion']");
    public SelenideElement continuarSoli = Selenide.$x("//*[@id='guardarSolicitud']");
    public SelenideElement continuarArchivos = Selenide.$x("/html/body/main/div/div[4]/div/form/div[4]/div/div/input[2]");
    public SelenideElement cargarArchivos = Selenide.$x("/html/body/main/div/div[4]/div/form[1]/table/tbody/tr[13]/td[2]/div/input[2]");
    public SelenideElement archivo1 = Selenide.$x(" /html/body/main/div/div[4]/div[2]/div/form[2]/table/tbody/tr[1]/td[4]/input");
    public SelenideElement archivo2 = Selenide.$x(" /html/body/main/div/div[4]/div[2]/div/form[3]/table/tbody/tr[1]/td[4]/input");
    public SelenideElement archivo3 = Selenide.$x(" /html/body/main/div/div[4]/div[2]/div/form[4]/table/tbody/tr[1]/td[4]/input");
    public SelenideElement archivo4 = Selenide.$x(" /html/body/main/div/div[4]/div[2]/div/form[5]/table/tbody/tr[1]/td[4]/input");
    public SelenideElement archivo5 = Selenide.$x(" /html/body/main/div/div[4]/div[2]/div/form[6]/table/tbody/tr[1]/td[4]/input");
    public SelenideElement archivo6 = Selenide.$x(" /html/body/main/div/div[4]/div[2]/div/form[7]/table/tbody/tr[1]/td[4]/input");
    public SelenideElement archivo7 = Selenide.$x(" /html/body/main/div/div[4]/div[2]/div/form[8]/table/tbody/tr[1]/td[4]/input");
    public SelenideElement archivo8 = Selenide.$x(" /html/body/main/div/div[4]/div[2]/div/form[9]/table/tbody/tr[1]/td[4]/input");
    public SelenideElement archivo9 = Selenide.$x(" /html/body/main/div/div[4]/div[2]/div/form[10]/table/tbody/tr[1]/td[4]/input");
    public SelenideElement archivo10 = Selenide.$x(" /html/body/main/div/div[4]/div[2]/div/form[11]/table/tbody/tr[1]/td[4]/input");
    public SelenideElement adjuntar = Selenide.$x("//*[@id='btnAnexar']");
    public SelenideElement btnCerrar = Selenide.$x("//*[@id='btnCerrar']");
    public SelenideElement btnSiguiente = Selenide.$x("//*[@id='siguienteButton']");
    public SelenideElement cerfF = Selenide.$x("//*[@id='certificate']");
    public SelenideElement keyfF = Selenide.$x("//*[@id='privateKey']");
    public SelenideElement passfF = Selenide.$x("//*[@id='privateKeyPassword']");
    public SelenideElement btnFirmar = Selenide.$x("//*[@id='btnSubmit']");
    public SelenideElement folio = Selenide.$x("/html/body/main/div/div[4]/div/div[4]/div/div/ul/li");
}
