package HACIENDA.Tramite40103;

import com.codeborne.selenide.Selenide;
import com.codeborne.selenide.SelenideElement;

public class MainPage40103 {
    public SelenideElement cerS = Selenide.$x("//*[@id='certificate']");
    public SelenideElement keyS = Selenide.$x("//*[@id='privateKey']");
    public SelenideElement pass = Selenide.$x("//*[@id='privateKeyPassword']");
    public SelenideElement btnIngres = Selenide.$x("//button[@onclick='ejecutarProcesoFirma(1)']");
    public SelenideElement btnFirmar = Selenide.$x("//*[@id='btnSubmit']");
    public SelenideElement selecRol = Selenide.$x("//*[@id='claveRol']");
    public SelenideElement btnacep = Selenide.$x("//button[@name='ingresar']");
    public SelenideElement Tramites = Selenide.$x("//*[@id='Trámites']");
    public SelenideElement SoliNew = Selenide.$x("/html/body/main/div/div[2]/div[1]/div[1]/div/nav/div/div[2]/ul/li[5]/ul/li[3]/a");
    public SelenideElement hacienda = Selenide.$x("//img[contains(@alt, 'General')]");
    public SelenideElement registroCodigoAlfanumerico = Selenide.$x("/html/body/main/div/div[3]/div/div[6]/ul/li[5]/a");
    public SelenideElement transporteTerrestre = Selenide.$x("/html/body/main/div/div[3]/div/div[6]/ul/li[5]/ul/li[1]/a");
    public SelenideElement atencionModificacion = Selenide.$x("/html/body/main/div/div[3]/div/div[6]/ul/li[5]/ul/li[1]/ul/li[3]/a");
    public SelenideElement choferes = Selenide.$x("/html/body/main/div/div[4]/div/form/div[2]/ul/li[3]/a/label");
    public SelenideElement nuevoChofer = Selenide.$x("/html/body/main/div/div[4]/div/form/div[2]/div/div[3]/div/div/div[1]/div[3]/div/div/input[3]");
    public SelenideElement curpChofer = Selenide.$x("//*[@id='curpCHN']");
    public SelenideElement rfcChofer = Selenide.$x("//*[@id='rfcCHN']");
    public SelenideElement buscarChofer = Selenide.$x("//*[@id='buscarChofer']");
    public SelenideElement entidadChofer = Selenide.$x("//*[@id='entidadFederativaCHN']");
    public SelenideElement municipioChofer = Selenide.$x("//*[@id='delegacionCHN']");
    public SelenideElement coloniaChofer = Selenide.$x("//*[@id='coloniaCHN']");
    public SelenideElement paisChofer = Selenide.$x("//*[@id='paisOrigenCHN']");
    public SelenideElement ciudadChofer = Selenide.$x("//*[@id='ciudadCHN']");
    public SelenideElement localidadChofer = Selenide.$x("//*[@id='localidadCHN']");
    public SelenideElement cpChofer = Selenide.$x("//*[@id='codigoPostalCHN']");
    public SelenideElement correoChofer = Selenide.$x("//*[@id='correoCHN']");
    public SelenideElement telefonoChofer = Selenide.$x("//*[@id='telefonoCHN']");
    public SelenideElement guardarChofer = Selenide.$x("//*[@id='guardarChofer']");
    public SelenideElement vehiculos = Selenide.$x("/html/body/main/div/div[4]/div[1]/form/div[2]/ul/li[4]/a/label");
    public SelenideElement nuevoVehiculoP = Selenide.$x("/html/body/main/div/div[4]/div[1]/form/div[2]/div/div[4]/div/div/div[1]/div[3]/div/div/input[3]");
    public SelenideElement vinVehiculo = Selenide.$x("//*[@id='vinVEH']");
    public SelenideElement tipoVehiculo = Selenide.$x("//*[@id='solicitudVehiculoTipoVehiculo']");
    public SelenideElement numPlaca = Selenide.$x("//*[@id='placasVEH']");
    public SelenideElement paisEmisor = Selenide.$x("//*[@id='solicitudVehiculoPaisEmisor']");
    public SelenideElement estadoVehiculo = Selenide.$x("//*[@id='estadoVEH']");
    public SelenideElement marcaVehiculo = Selenide.$x("//*[@id='marcaVEH']");
    public SelenideElement modeloVehiculo = Selenide.$x("//*[@id='modeloVEH']");
    public SelenideElement añoVehiculo = Selenide.$x("//*[@id='anioVehiculoVEH']");
    public SelenideElement transponderVehiculo = Selenide.$x("//*[@id='transponderVEH']");
    public SelenideElement colorVehiculo = Selenide.$x("//*[@id='solicitudVehiculoColor']");
    public SelenideElement numEconomico = Selenide.$x("//*[@id='numeroEconomicoVEH']");
    public SelenideElement guardarVehiculo = Selenide.$x("//*[@id='guardarVehiculo']");
    public SelenideElement vehiculoArrastre = Selenide.$x("/html/body/main/div/div[4]/div[1]/form/div[2]/div/div[4]/div/ul/li[2]/a/label");
    public SelenideElement nuevoVehiculoA = Selenide.$x("/html/body/main/div/div[4]/div[1]/form/div[2]/div/div[4]/div/div/div[2]/div[3]/div/div/input[3]");
    public SelenideElement vinVehiculoA = Selenide.$x("//*[@id='vinVEHARR']");
    public SelenideElement tipoVehiculoA = Selenide.$x("//*[@id='solicitudVehiculoArrastreTipoVehiculo']");
    public SelenideElement numPlacaA = Selenide.$x("//*[@id='placasVEHARR']");
    public SelenideElement paisEmisorA = Selenide.$x("//*[@id='solicitudVehiculoArrastrePaisEmisor']");
    public SelenideElement estadoVehiculoA = Selenide.$x("//*[@id='estadoVEHARR']");
    public SelenideElement colorVehiculoA = Selenide.$x("//*[@id='solicitudVehiculoArrastreColor']");
    public SelenideElement numEconomicoA = Selenide.$x("//*[@id='numeroEconomicoArraVEHARR']");
    public SelenideElement guardarSoli = Selenide.$x("//*[@id='guardarSolicitud']");
    public SelenideElement folio = Selenide.$x("/html/body/main/div/div[4]/div/div[4]/div/div/ul/li[1]");
}
