package HACIENDA.Tramite32502;

import com.codeborne.selenide.Selenide;
import com.codeborne.selenide.SelenideElement;

public class MainPage32502 {
    public SelenideElement cerS = Selenide.$x("//*[@id='certificate']");
    public SelenideElement keyS = Selenide.$x("//*[@id='privateKey']");
    public SelenideElement pass = Selenide.$x("//*[@id='privateKeyPassword']");
    public SelenideElement btnIngres = Selenide.$x("//button[@onclick='ejecutarProcesoFirma(1)']");
    public SelenideElement btnFirmar = Selenide.$x("//*[@id='btnSubmit']");
    public SelenideElement folio = Selenide.$x("/html/body/main/div/div[4]/div/div[4]/div/div/ul/li");
    public SelenideElement selecRol = Selenide.$x("//*[@id='claveRol']");
    public SelenideElement btnacep = Selenide.$x("//button[@name='ingresar']");
    public SelenideElement Tramites = Selenide.$x("//*[@id='Trámites']");
    public SelenideElement SoliNew = Selenide.$x("/html/body/main/div/div[2]/div[1]/div[1]/div/nav/div/div[2]/ul/li[5]/ul/li[3]/a");
    public SelenideElement hacienda = Selenide.$x("//img[contains(@alt, 'General')]");
    public SelenideElement registrosComercioExt = Selenide.$x("/html/body/main/div/div[3]/div/div[8]/ul/li/a");
    public SelenideElement envioAvisos = Selenide.$x("/html/body/main/div/div[3]/div/div[8]/ul/li/ul/li[6]/a");
    public SelenideElement avisoImpTemporal106 = Selenide.$x("/html/body/main/div/div[3]/div/div[8]/ul/li/ul/li[6]/ul/li[2]/a");
    public SelenideElement aviso = Selenide.$x("/html/body/main/div/div[4]/div/form/div[2]/ul/li[2]/a");
    public SelenideElement razonImportador = Selenide.$x("//*[@id='idRazonSocial']");
    public SelenideElement rfcImportador = Selenide.$x("//*[@id='idRFC']");
    public SelenideElement taxID = Selenide.$x("//*[@id='idTaxID']");
    public SelenideElement fracArancelaria = Selenide.$x("//*[@id='solicitud.mercanciaST.cveFraccionArancelaria']");
    public SelenideElement fracRegla = Selenide.$x("//*[@id='solicitud.mercanciaST.reglaFraccion']");
    public SelenideElement NICO = Selenide.$x("//*[@id='idNICO']");
    public SelenideElement valorUSD = Selenide.$x("//*[@id='idValorUSD']");
    public SelenideElement marca = Selenide.$x("//*[@id='idMarca']");
    public SelenideElement pesoKG = Selenide.$x("//*[@id='idPesoKg']");
    public SelenideElement fechaImport = Selenide.$x("//*[@id='idFechaInicioVigencia']");
    public SelenideElement selecFecha = Selenide.$x("/html/body/div[6]/table/tbody/tr[5]/td[2]/a");
    public SelenideElement numSerie = Selenide.$x("//*[@id='idNumSerie']");
    public SelenideElement descripcionMerc = Selenide.$x("//*[@id='idDescMerc']");
    public SelenideElement nombreComercial = Selenide.$x("//*[@id='idNomComercial']");
    public SelenideElement entidad = Selenide.$x("//*[@id='solicitud.direccionST.entidadFederativa']");
    public SelenideElement municipio = Selenide.$x("//*[@id='solicitud.direccionST.delegacionMunicipio']");
    public SelenideElement colonia = Selenide.$x("//*[@id='solicitud.direccionST.colonia']");
    public SelenideElement calle = Selenide.$x("//*[@id='idCalle']");
    public SelenideElement numExt = Selenide.$x("//*[@id='idNoExterior']");
    public SelenideElement numInt = Selenide.$x("//*[@id='idInterior']");
    public SelenideElement CP = Selenide.$x("//*[@id='idCodPostal']");
    public SelenideElement patenteAgenteA = Selenide.$x("//*[@id='idPatAutAgeAdu']");
    public SelenideElement rfcAgente = Selenide.$x("//*[@id='idRfcAgentAdu']");
    public SelenideElement numPedimento = Selenide.$x("//*[@id='idNumPedimento']");
    public SelenideElement aduanaImp = Selenide.$x("//*[@id='solicitud.pedimentoST.clave']");
    public SelenideElement manifiesto = Selenide.$x("//*[@id='manifiesto0']");
    public SelenideElement btnContinuar = Selenide.$x("/html/body/main/div/div[4]/div/form/div[2]/div/div[4]/div/div/div[2]/input[1]");
    public SelenideElement btnArchivos = Selenide.$x("/html/body/main/div/div[4]/div/form/div[4]/div/div/input[2]");
    public SelenideElement btnCargarArch = Selenide.$x("/html/body/main/div/div[4]/div/form[1]/table/tbody/tr[12]/td[2]/div/input[2]");
    public SelenideElement archivo1 = Selenide.$x("/html/body/main/div/div[4]/div[2]/div/form[2]/table/tbody/tr[1]/td[4]/input");
    public SelenideElement archivo2 = Selenide.$x("/html/body/main/div/div[4]/div[2]/div/form[3]/table/tbody/tr[1]/td[4]/input");
    public SelenideElement archivo3 = Selenide.$x("/html/body/main/div/div[4]/div[2]/div/form[4]/table/tbody/tr[1]/td[4]/input");
    public SelenideElement archivo4 = Selenide.$x("/html/body/main/div/div[4]/div[2]/div/form[5]/table/tbody/tr[1]/td[4]/input");
    public SelenideElement archivo5 = Selenide.$x("/html/body/main/div/div[4]/div[2]/div/form[6]/table/tbody/tr[1]/td[4]/input");
    public SelenideElement archivo6 = Selenide.$x("/html/body/main/div/div[4]/div[2]/div/form[7]/table/tbody/tr[1]/td[4]/input");
    public SelenideElement archivo7 = Selenide.$x("/html/body/main/div/div[4]/div[2]/div/form[8]/table/tbody/tr[1]/td[4]/input");
    public SelenideElement archivo8 = Selenide.$x("/html/body/main/div/div[4]/div[2]/div/form[9]/table/tbody/tr[1]/td[4]/input");
    public SelenideElement archivo9 = Selenide.$x("/html/body/main/div/div[4]/div[2]/div/form[10]/table/tbody/tr[1]/td[4]/input");
    public SelenideElement adjuntarArchivos = Selenide.$x("//*[@id='btnAnexar']");
    public SelenideElement btnCerrar = Selenide.$x("//*[@id='btnCerrar']");
    public SelenideElement btnSiguiente = Selenide.$x("/html/body/main/div/div[4]/div[1]/form[2]/div[2]/div/input[2]");
}
