package HACIENDA.TramiteR15;
import com.codeborne.selenide.Condition;
import com.codeborne.selenide.SelenideElement;
import static com.codeborne.selenide.Selenide.$x;
import static com.codeborne.selenide.Selenide.*;
// page_url = https://wwwqa.ventanillaunica.gob.mx/ventanilla-HA/authentication.action?showLogin=%22;
public class MainPageR15 {
    //    datos para firma
    public SelenideElement cerS = $x("//*[@id='certificate']");
    public SelenideElement keyS = $x("//*[@id='privateKey']");
    public SelenideElement pass = $x("//*[@id='privateKeyPassword']");
    public SelenideElement btnIngresFs = $x("//button[@onclick='ejecutarProcesoFirma(1)']");
    public SelenideElement btnFinal = $x("/html/body/main/div/div[4]/div/form/div[1]/table/tbody/tr[7]/td/input");
    public SelenideElement selecRol = $x("//*[@id='claveRol']");
    public SelenideElement btnacep = $x("//button[@name='ingresar']");
    public SelenideElement Tramites = $x("//*[@id='Trámites']");
    public SelenideElement SoliNew = $x("/html/body/main/div/div[2]/div[1]/div[1]/div/nav/div/div[2]/ul/li[5]/ul/li[3]/a");
    public SelenideElement hacienda = $x("//img[contains(@alt, 'General')]");
    public SelenideElement linkAvisosAgaSat = $x("/html/body/main/div/div[3]/div/div[6]/ul/li[19]/a");
    public SelenideElement R15 = $x("/html/body/main/div/div[3]/div/div[6]/ul/li[19]/ul/li[8]/a");
    public SelenideElement linkDetalle = $x("//*[@id='ui-id-2']");
    public SelenideElement ejercicio = $x("/html/body/main/div/div[4]/div/form/div[2]/div[2]/div/div[2]/div[1]/div[2]/select/option[4]");
    public SelenideElement declaracion = $x("/html/body/main/div/div[4]/div/form/div[2]/div[2]/div/div[2]/div[3]/div[2]/select/option[6]");
    public SelenideElement periodo = $x("/html/body/main/div/div[4]/div/form/div[2]/div[2]/div/div[3]/div/div[2]/select/option[7]");
    public SelenideElement obligaciones = $x("/html/body/main/div/div[4]/div/form/div[2]/div[2]/div/div[5]/div/div/div/div/div[1]/input");
    public SelenideElement aduana = $x("/html/body/main/div/div[4]/div/form/div[2]/div[2]/div/div[7]/div/div[2]/select/option[2]");
    public SelenideElement superficie = $x("/html/body/main/div/div[4]/div/form/div[2]/div[2]/div/div[9]/div[1]/div[2]/input");
    public SelenideElement capacidad = $x("/html/body/main/div/div[4]/div/form/div[2]/div[2]/div/div[9]/div[2]/div[2]/input");
    public SelenideElement rfc = $x("/html/body/main/div/div[4]/div/form/div[2]/div[2]/div/div[9]/div[3]/div[2]/input");
    public SelenideElement autorizacion = $x("/html/body/main/div/div[4]/div/form/div[2]/div[2]/div/div[10]/div[1]/div[2]/input");
    public SelenideElement constancia = $x("/html/body/main/div/div[4]/div/form/div[2]/div[2]/div/div[10]/div[2]/div[2]/input");
    public SelenideElement recintoDictamen = $x("/html/body/main/div/div[4]/div/form/div[2]/div[2]/div/div[12]/div[2]/input[1]");
    public SelenideElement ingresoBrutoDeterminacion = $x("/html/body/main/div/div[4]/div/form/div[2]/div[2]/div/div[17]/div/div/input[1]");
    public SelenideElement tipoMovimiento = $x("/html/body/main/div/div[4]/div[2]/form/div[1]/div[1]/div[1]/div[2]/select/option[2]");
    public SelenideElement toneladas = $x("/html/body/main/div/div[4]/div[2]/form/div[1]/div[1]/div[2]/div[2]/input");
    public SelenideElement ingresoPor = $x("/html/body/main/div/div[4]/div[2]/form/div[1]/div[1]/div[3]/div[2]/select/option[3]");
    public SelenideElement ingresoBruto = $x("/html/body/main/div/div[4]/div[2]/form/div[1]/div[2]/div/div[2]/input");
    public SelenideElement aceptarDeterminacion = $x("/html/body/main/div/div[4]/div[2]/form/div[1]/div[4]/div/div/input[1]");
    public SelenideElement datosCorrectos = $x("//div[contains(@class, 'ui-dialog-buttonpane')]//button[contains(text(), 'Aceptar')]");
    public SelenideElement ingresoServiciosDistintos = $x("/html/body/main/div/div[4]/div/form/div[2]/div[2]/div/div[20]/div/div/input[1]");
    public SelenideElement tipoMovimiento2 = $x("/html/body/main/div/div[4]/div[2]/form/div[1]/div[1]/div[1]/div[2]/select/option[2]");
    public SelenideElement servicio = $x("/html/body/main/div/div[4]/div[2]/form/div[1]/div[1]/div[2]/div[2]/select/option[4]");
    public SelenideElement importe = $x("/html/body/main/div/div[4]/div[2]/form/div[1]/div[1]/div[3]/div[2]/input");
    public SelenideElement aceptarServicioDistinto = $x("/html/body/main/div/div[4]/div[2]/form/div[1]/div[3]/div/div/input[1]");
    public SelenideElement datosCorrectos2 = $$("button.btn.btn-primary").filter(Condition.text("Aceptar")).first();
    public SelenideElement pagoSaldoCompensar = $x("/html/body/main/div/div[4]/div/form/div[2]/div[2]/div/div[27]/div[1]/div[2]/input");
    public SelenideElement aplicarSaldoCompensar = $x("/html/body/main/div/div[4]/div/form/div[2]/div[2]/div/div[27]/div[2]/div[2]/input");
    public SelenideElement pagoSaldoPendiente = $x("/html/body/main/div/div[4]/div/form/div[2]/div[2]/div/div[30]/div[1]/div[2]/input");
    public SelenideElement aplicarSaldoPendienteAduana = $x("/html/body/main/div/div[4]/div/form/div[2]/div[2]/div/div[30]/div[2]/div[2]/input");
    public SelenideElement SaldoPendienteFideicomiso = $x("/html/body/main/div/div[4]/div/form/div[2]/div[2]/div/div[33]/div[1]/div[2]/input");
    public SelenideElement aplicarSaldoPendienteFideicomiso = $x("/html/body/main/div/div[4]/div/form/div[2]/div[2]/div/div[33]/div[2]/div[2]/input");
    public SelenideElement continuar = $x("/html/body/main/div/div[4]/div/form/div[3]/div/div/div[2]/input[1]");
    public SelenideElement folio = $x("/html/body/main/div/div[4]/div/div[4]/div/div/ul/li");
}